version: "3.8"

services:
  api:
    image: harezmi06/api:lts
    restart: on-failure
    ports:
      - "3000:3000"

    deploy:
      mode: replicated
      replicas: 5
      update_config:
        parallelism: 2
        delay: 5s
        order: stop-first
    networks:
      - gaziNet


  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 2
        delay: 5s
        order: stop-first
    networks:
      - gaziNet

networks:
  gaziNet:
    driver: overlay
